"""Write the versioned battle HUD contract; no network calls."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
assets = []
anchor = "res://Design/Sunflower-Defense-Art-Style-Guide.md; res://tmp/battle-ui-v3-baseline/hud-day-runtime.png; res://assets/ui/generated/battle_hud/runtime_primary_action_normal_v2.png. Deep ink-green glass, thin oxidized aged brass, sparse leaf engraving, warm upper-left highlights, botanical storybook brushwork."
comfort = ["Low contrast centers; restrained warm highlights without bloom", "Sparse edge engraving; no flashing or motion implied", "Clear silhouettes at 160 and 176 pixels; quiet runtime text areas"]
avoid = ["pixel art", "photography", "candy saturation", "neon", "chrome", "plastic", "dense decoration", "baked UI", "text", "watermark", "logo"]
for id_,kind,role,size,display,safe,composition,node,prop,margins in [
    ("primary_action_frame","button","Identify the phase's one decisive action: start night or sunburst",[512,384],[160,114],[28,25,28,32],"One horizontal rounded rectangular greenhouse action frame, aspect 4:3. Stable narrow brass edge, sparse leaf relief only in corners; empty ink-green glass center, no icons. Orthographic UI view; upper-left soft light. Identical silhouette for all states; only tint and rim luminance change at runtime.","PrimaryActionButton/StartNightButton","theme_override_styles/normal",[36,32,36,32]),
    ("tactical_bezel","decoration","Identify the combined light-network and directional-threat tactical instrument",[512,512],[176,176],[42,42,42,42],"One perfectly centered circular thin aged-brass greenhouse instrument rim; sparse botanical etching, real transparent central opening for Godot radar and threats; no needles, ticks, lettering, stand, protruding hardware. Upper-left soft warm highlight; neutral daytime and nighttime state.","TacticalInstrumentFrame/TacticalBezelArt","texture",None),
]:
    prompt = "1. Game asset use: " + role + ".\n2. Runtime size and safe area: output " + str(size) + " pixels, Godot display " + str(display) + " pixels. Full artwork must fill canvas with 8px outer transparent margin; no cropping; content safe margins left/top/right/bottom " + str(safe) + ".\n3. Project visual anchor: " + anchor + "\n4. Composition and state contract: " + composition + "\n5. Comfort: " + "; ".join(comfort) + ".\n6. Project and AI exclusions: " + "; ".join(avoid) + "; no text, no watermark, no logo, no unintended objects, no baked UI, no alternatives or contact sheet.\n7. Transparent output: real RGBA transparent exterior, clean unpremultiplied alpha edges, no solid backdrop, checkerboard or environment."
    output={"path":f"res://art_source/generated/mm_tools/battle_hud_v3/{id_}.png","size":size,"mode":"nine_patch" if margins else "full_image"}
    runtime={"path":f"res://assets/ui/generated/battle_hud_v3/{id_}.png","size":size,"mode":output["mode"]}
    if margins:
        output["patch_margin"]=margins; runtime["patch_margin"]=margins; runtime["content_margin"]=[12,16,12,16]
    bindings=[{"node":node,"property":prop}]
    if kind=="button":
        runtime.pop("path")
        runtime["path_pattern"]="res://assets/ui/generated/battle_hud_v3/primary_action_{state}.png"
        runtime["derived_by"]="res://art_source/process_battle_hud_v3.py"
        runtime["size"]=[160,114]
        runtime["patch_margin"]=[30,23,30,23]
        bindings=[{"node":"PrimaryActionButton/"+button,"property_map":{state:"theme_override_styles/"+state for state in ["normal","hover","pressed","disabled"]}} for button in ["StartNightButton","SunburstButton"]]
    assets.append({"id":id_,"kind":kind,"role":role,"states":["normal","hover","pressed","disabled"] if kind=="button" else ["neutral"],"generation":{"enabled":True,"provider":"mm-api","model":"gpt-image-2","transparent":True,"prompt":prompt},"output":output,"runtime":runtime,"ui_spec":{"purpose":role,"display_size":display,"content_safe_area":safe,"layout":composition,"state_contract":"One generated master; button hover/pressed/disabled derive from its exact alpha; bezel remains neutral","negative":avoid},"bindings":bindings})

native = [("mother_status","panel","MotherStatusPanel","theme_override_styles/panel"),("phase_banner","panel","PhaseBanner","theme_override_styles/panel"),("resource_panel","panel","ResourcePanel","theme_override_styles/panel"),("phase_tray","panel","PhaseActionTray","theme_override_styles/panel"),("day_actions","panel","PhaseActionTray/DayActionPanel","theme_override_styles/panel"),("night_hand","panel","PhaseActionTray/NightHandPanel","theme_override_styles/panel"),("health_bar","bar","MotherStatusPanel","modulate"),("selection_detail","panel","SelectionDetailPanel","theme_override_styles/panel"),("notification","panel","NotificationBanner","theme_override_styles/panel"),("mother_choices","panel","MotherChoiceOverlay/MotherChoicePanel","theme_override_styles/panel"),("result","panel","ResultPanel","theme_override_styles/panel"),("tactical_fallback","panel","TacticalInstrumentFrame","theme_override_styles/panel"),("button_states","button","PrimaryActionButton/StartNightButton","theme_override_styles/hover")]
for id_,kind,node,prop in native:assets.append({"id":id_,"kind":kind,"role":"Godot native style or preserved existing resource; " + id_,"generation":{"enabled":False},"bindings":[{"node":node,"property":prop}]})
for id_,node in [("phase_text","PhaseBanner/PhaseContent/PhaseLabel"),("wave_text","PhaseBanner/PhaseContent/PhaseDetailRow/WaveLabel"),("timer_text","PhaseBanner/PhaseContent/PhaseDetailRow/TimerLabel"),("enemy_text","PhaseBanner/PhaseContent/PhaseDetailRow/EnemyCountLabel"),("energy_text","ResourcePanel/ResourceRow/EnergyValue"),("seed_text","ResourcePanel/ResourceRow/SeedLabel"),("cost_text","PrimaryActionButton/CostOverlay/SunburstCostLabel"),("shortcut_text","PrimaryActionButton/CostOverlay/PrimaryShortcut"),("selection_title","SelectionDetailPanel/SelectionContent/SelectionTitle"),("selection_text","SelectionDetailPanel/SelectionContent/SelectionValue")]:assets.append({"id":id_,"kind":"text","role":"Live localized text drawn by Godot fonts","generation":{"enabled":False},"bindings":[{"node":node,"property":"text"}]})
evidence=[{"kind":"art_guide","source":"res://Design/Sunflower-Defense-Art-Style-Guide.md","reason":"Approved project botanical storybook art guide"},{"kind":"accepted_manifest","source":"res://docs/superpowers/specs/2026-09-29-battle-hud-redesign.md","reason":"Existing approved HUD layout research and gameplay boundary; reuse stable phase-specific interaction anchors"},{"kind":"accepted_manifest","source":"res://docs/mm-tools-battle-hud-v3-stage12.md","reason":"Current requested optimization within existing approved greenhouse direction; stage 1 concrete findings and stage 2 contract"}]
for name,state in [("hud-day-runtime.png","day deployment"),("hud-night-runtime.png","night with four cards, insufficient energy and boss threat"),("hud-mother-choice-runtime.png","mother upgrade choices")]:evidence.append({"kind":"runtime_screenshot","source":"res://tmp/battle-ui-v3-baseline/"+name,"reason":"Actual Godot tests/battle_ui_v3_capture.gd, 1280x720, state " + state})
for path,usage in [("assets/core/ART_CORE_MotherFlower_Healthy.png","status portrait"),("assets/ui/UI_ICON_ThornFlower.png","deployment action"),("assets/ui/UI_ICON_PrismFlower.png","deployment action"),("assets/ui/UI_ICON_Repair.png","repair action"),("assets/ui/generated/battle_hud/tactical_instrument_frame.png","instrument brass geometry"),("assets/ui/generated/battle_hud/runtime_primary_action_normal_v2.png","existing action brass and glass")]:evidence.append({"kind":"runtime_asset","source":"res://"+path,"reason":usage})
for url,reason in [("https://store.steampowered.com/app/2239150/Thronefall/","low-obstruction center and day/night-dependent actions"),("https://store.steampowered.com/app/644930/They_Are_Billions/","stable resource anchors and grouped build operations")]:evidence.append({"kind":"external_reference","source":url,"reason":"layout-only; " + reason + "; verified commercial Steam listing 2026-09-30; existing approved research provides UI analysis; not an art authority"})
manifest={"$schema":"../schemas/mm_art_manifest.schema.json","schema_version":1,"feature":"battle_hud_v3","scene":"res://scenes/main.tscn","root_node":"BattleHudRoot","style":{"reference_images":["res://tmp/battle-ui-v3-baseline/hud-day-runtime.png","res://tmp/battle-ui-v3-baseline/hud-night-runtime.png"],"prompt_prefix":"Project greenhouse botanical storybook UI, as specified by ordered per-resource contracts.","evidence":evidence,"sprite_gen_contract":"sprite-gen/docs/gen.md","visual_anchor":anchor,"comfort_constraints":comfort,"avoid":avoid},"assets":assets}
(root/"art_source/manifests/battle_hud_v3.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
