"""V4 refinement contract, reusing V3 gameplay geometry and existing illustrations."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
old=json.loads((root/'art_source/manifests/battle_hud_v3.json').read_text(encoding='utf-8'))
style=old['style']
style['reference_images']=['res://output/imagegen/previews/battle-hud-v3-1280x720-hud-day-runtime.png','res://output/imagegen/previews/battle-hud-v3-1280x720-hud-night-runtime.png']
style['evidence']=[x for x in style['evidence'] if x['kind'] not in ['external_reference','runtime_screenshot','runtime_asset']]
for path,reason in [('assets/core/ART_CORE_MotherFlower_Healthy.png','Mother portrait and sunlight card category'),('assets/nodes/ART_NODE_LightBud_Healthy.png','Day deployment and healing card category'),('assets/ui/UI_ICON_Repair.png','Day repair tool/category illustration distinct from deployment'),('assets/plants/ART_PLANT_ThornFlower_Powered.png','Day thorn and root combat category illustration'),('assets/plants/ART_PLANT_PrismFlower_Powered.png','Day prism and piercing combat category illustration'),('assets/ui/generated/battle_hud_v3/primary_action_normal.png','Accepted V3 hand-painted brass and glass anchor; reused'),('assets/ui/generated/battle_hud_v3/tactical_bezel.png','Accepted V3 botanical brass upper-left lighting anchor; reused')]:style['evidence'].append({'kind':'runtime_asset','source':'res://'+path,'reason':reason})
style['evidence'].append({'kind':'accepted_manifest','source':'res://docs/mm-tools-battle-hud-v4-stage12.md','reason':'User requested visual polish; reuse V3 accepted gameplay geometry without new layout'})
for p in style['reference_images']:style['evidence'].append({'kind':'runtime_screenshot','source':p,'reason':'V3 actual Godot 1280x720 day/night prior visual baseline'})
style['visual_anchor']='Approved botanical greenhouse: hand-painted ink-green glass with blue-grey shaded edges; narrow worn brass double rim; sparse flattened leaf embossing at corners; soft upper-left light; warm pale text; clean quiet readout centers. References res://Design/Sunflower-Defense-Art-Style-Guide.md, res://assets/ui/generated/battle_hud_v3/primary_action_normal.png and res://assets/ui/generated/battle_hud_v3/tactical_bezel.png.'
assets=[]
for id_,kind,size,display,role,layout,bindings in [
 ('status_frame','panel',[768,256],[304,88],'Unified mother health, phase and resource readout frame','Single 3:1 horizontal greenhouse frame. Thin double brass rim, subtly blue-grey ink-green glass with faint hand-painted edge shading, sparse pressed-leaf relief only in four corners. Empty low-noise central 85 percent. No flower portraits or status indicators.',[{'node':n,'property':'theme_override_styles/panel'} for n in ['MotherStatusPanel','PhaseBanner','ResourcePanel']]),
 ('specimen_card_frame','button',[512,512],[142,110],'Battle action botanical specimen card framing existing live plant illustration, name and cost','Single compact nearly square specimen-window card. Narrow copper-brass rim with small upper corner leaf clasps. Quiet upper illustration window and lower dark green record-label region, no actual separator words. No portraits, plants, icons or costs; runtime supplies them. Empty center with restrained grain.',[{'scope':'component','node':'.','property_map':{s:'theme_override_styles/'+s for s in ['normal','hover','pressed','disabled']}}]),
 ('action_tray_frame','panel',[1024,256],[620,126],'Low-weight shared day/night action tray beneath interactive cards','One 4:1 shallow tray frame. Transparent dark ink-green glass inset, fine worn brass rail and lightly brushed greenhouse wood edge. Corner leaf impressions only at tiny extreme ends. Calm empty center; no cards, flowers, plaques or buttons.',[{'node':'PhaseActionTray','property':'theme_override_styles/panel'}]),
]:
 prompt=f'1. Game asset use: {role}.\n2. Runtime display size and safe area: source {size}, runtime {display}; nine-slice only straight edges and quiet center, corners uniformly scale; transparent outer margin 8px; 20px runtime text and input safe margins.\n3. Project visual anchor: {style["visual_anchor"]}\n4. Composition and state contract: {layout} Orthographic view, upper-left soft light. Single neutral master; card states preserve exact alpha geometry through deterministic tint.\n5. Comfort constraints: low contrast center, sparse edge texture, no bloom, motion or flashing; subtle material readable at declared runtime size.\n6. Project and AI exclusions: no neon, plastic, photography, pixel art, dense ornament, bright glow, text, watermark, logo, unintended objects, baked UI, alternatives or contact sheet.\n7. Transparent output: real RGBA exterior and clean alpha; no solid backdrop, checkerboard or environment; glass inset may be translucent.'
 runtime={'path':f'res://assets/ui/generated/battle_hud_v4/{id_}.png','size':display,'mode':'nine_patch','patch_margin':[18,16,18,16],'content_margin':[12,8,12,8],'derived_by':'res://art_source/process_battle_hud_v4.py'}
 if kind=='button':
  runtime.pop('path');runtime['path_pattern']='res://assets/ui/generated/battle_hud_v4/specimen_card_{state}.png';runtime['content_margin']=[8,8,8,8]
  runtime['source_window_fraction']=0.70;runtime['runtime_window_height']=54;runtime['brightness']=0.68
 else:
  runtime['brightness']=0.68 if id_=='status_frame' else 0.62
 assets.append({'id':id_,'kind':kind,'role':role,'states':['normal','hover','pressed','disabled'] if kind=='button' else ['neutral'],'generation':{'enabled':True,'provider':'mm-api','model':'gpt-image-2','transparent':True,'prompt':prompt},'output':{'path':f'res://art_source/generated/mm_tools/battle_hud_v4/{id_}.png','size':size,'mode':'nine_patch','patch_margin':[36,32,36,32]},'runtime':runtime,'ui_spec':{'purpose':role,'display_size':display,'content_safe_area':[20,16,20,16],'layout':layout,'state_contract':'Neutral master; all card states share exact alpha','negative':['text','watermark','logo','flowers','portraits','baked UI','busy center']},'bindings':bindings})
for a in old['assets']:
 if not a['generation']['enabled']:assets.append(a)
for id_,path in [('specimen_illustration','SpecimenArt'),('specimen_title','SpecimenTitle'),('specimen_cost','SpecimenCost')]:assets.append({'id':id_,'kind':'text' if id_!='specimen_illustration' else 'portrait','role':'Existing project category illustration or runtime card text; no new generated semantic artwork','generation':{'enabled':False},'bindings':[{'scope':'component','node':path,'property':'text' if id_!='specimen_illustration' else 'texture'}]})
assets.append({'id':'specimen_selection','kind':'decoration','role':'Native thin warm-brass outline indicates the currently selected combat card without lightening its full face','generation':{'enabled':False},'bindings':[{'scope':'component','node':'SpecimenSelection','property':'visible'}]})
manifest={'$schema':'../schemas/mm_art_manifest.schema.json','schema_version':1,'feature':'battle_hud_v4','scene':old['scene'],'root_node':old['root_node'],'style':style,'assets':assets}
(root/'art_source/manifests/battle_hud_v4.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

