extends SceneTree

func _initialize() -> void:
	var game = load("res://scripts/game.gd").new()
	var mother = load("res://scripts/mother_flower.gd").new()
	game.add_child(mother)
	game.mother_flower = mother
	mother.reset_state()
	mother.health = 200
	assert(mother.choose_path("root_heart"))
	assert(mother.max_health == 360 and mother.health == 260)
	mother.on_night_started()
	mother.advance_root_recovery(1)
	assert(is_equal_approx(mother.health, 260.4))
	mother.on_day_started()
	mother.advance_root_recovery(10)
	assert(is_equal_approx(mother.health, 260.4))
	assert(mother.choose_evolution("mother_sap_01"))
	var plant = load("res://scripts/plant.gd").new()
	game.add_child(plant)
	game.plants.append(plant)
	plant.max_health = 100; plant.health = 20
	mother.on_night_started()
	mother.advance_root_recovery(4.9)
	assert(plant.health == 20)
	mother.advance_root_recovery(0.1)
	assert(plant.health == 30)
	for rank in range(2, 7): assert(mother.choose_evolution("mother_sap_%02d" % rank))
	mother.on_night_started()
	mother.advance_root_recovery(3)
	assert(plant.health == 45)
	plant.temporary_lifetime = 10
	mother.advance_root_recovery(3)
	assert(plant.health == 45)
	mother.health = 0
	mother.advance_root_recovery(10)
	assert(mother.health == 0)
	game.free()
	var evo = load("res://scripts/mother_evolution.gd").new()
	evo.choose_path("dawn_pulse")
	assert(evo.get_effect_value("pulse_stun_normal", 0.5) == 0.5)
	evo.choose_upgrade("mother_quelling_01")
	assert(evo.get_effect_value("pulse_stun_normal", 0.5) == 0.7)
	for rank in range(2, 7): assert(evo.choose_upgrade("mother_quelling_%02d" % rank))
	assert(evo.get_effect_value("pulse_stun_normal", 0.5) == 1.0)
	var failures = load("res://tests/test_mother_evolution.gd").new().run()
	assert(failures.is_empty(), str(failures))
	print("MOTHER CORE TESTS PASSED")
	quit()
